### ISSUE TITLE
Issue in reference state calculations for model data

### ISSUE THREAD

**Issue by Pragallva** [csyhuang/hn2016_falwa#102]
While applying the class QGFieldNHN22 to a model dataset, I encountered an unrealistic reference state and negative FAWA values in the tropics which is not right (FAWA should always be positive). This issue seems to be coming from the part of the code that computes the reference state.

The code works perfectly fine when applied to ERAI and ERA5 datasets but they don't work on NorESM model output, for example. The reason being that the current version of falwa assumes dlat = dlon which is true for the case of ERA datasets but may not work for other model data where the latitude and longitude grid spacings may be different.

Good news is that this looks like an easy fix. The issue seems to be resolved when appropriate changes are made in the fortran codes, particularly in compute_qref_and_fawa_first.f90.

**Comment by csyhuang** [comment]
@Pragallva FYI I created a pull request to `master` for @chpolste to review which includes your commits: #105
