### ISSUE TITLE
A potential bug in the 'u_baro' calculation of FALWA v.1.2.0

### ISSUE THREAD

**Issue by sandrolubis** [csyhuang/hn2016_falwa#108]
Hi all, after updating to FALWA v1.2.0, I spotted a potential bug in u_baro calculation where the output mirrors - i.e., SH = NH. I checked the 'interpolated_u' data; they are correct. Only 'u_baro' shows this issue. See the attached plot. 

![ubaro_falwa120](https://github.com/csyhuang/hn2016_falwa/assets/26489636/5d3627c6-7b45-4015-801c-fb3a91a10391)

**Comment by csyhuang** [comment]
@sandrolubis Thanks for reporting the bug! 
@chpolste Thanks for figuring out the cause of this issue! I think your solution works (maybe also define explicitly `jstart` and `jend` in the loop?)! Do you have time to submit a bugfix PR (and update version number to `v1.2.1`)? If not, I will do it this weekend after work.
