### ISSUE TITLE
gfortran compile error hn2016_falwa/interpolate_fields.f90

### ISSUE THREAD

**Issue by semvijverberg** [csyhuang/hn2016_falwa#12]
Dear C. Huang,

I get an error like:
'''Warning: Unused variable ‘ylat’ declared at (1) [-Wunused-variable]
FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
error: Command "/usr/local/bin/gfortran -Wall -g -fno-second-underscore -m64 -fPIC -O3 -funroll-loops -Ibuild/src.macosx-10.6-x86_64-2.7/build/src.macosx-10.6-x86_64-2.7 -I/Users/semvijverberg/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/semvijverberg/anaconda2/include/python2.7 -c -c hn2016_falwa/interpolate_fields.f90 -o build/temp.macosx-10.6-x86_64-2.7/hn2016_falwa/interpolate_fields.o" failed with exit status 1'''

The full output is in the .txt output. To do this installation I installed the gfortran compiler 'gfortran-8.1-bin.tar.gz'. I tried installing both the normal and the test version, but I get the same error.  I do not know what my next step would be to solve/unravel this problem. I hope you can help me. 

I am now expert, perhaps I am doing something wrong.. 

Thanks in advance!
Sem

[interpolate_fields.f90_error.txt](https://github.com/csyhuang/hn2016_falwa/files/2290310/interpolate_fields.f90_error.txt)

**Comment by csyhuang** [comment]
Hi Sem,

Have you solved the issues? Please keep me updated, or I'll close the ticket in 10 days.

Thanks,

Clare

**Comment by semvijverberg** [comment]
Dear Clare,

Thanks a lot for your reminder!

I have been quite busy with different projects so this was set on hold. I will try to look into it next week, sorry for the delay. If I do not find the time before next Friday, feel free to close the ticket and thanks for your help up to now.

Kind regards,
Sem Vijverberg

PhD Candidate, Dept. of Water and Climate Risk (WCR)
Institute for Environmental studies

[cid:99817534-6418-49DD-B5DB-48B7EEB072AB@vu.local]
T +31 20 59 88 941  | sem.vijverberg@vu.nl<mailto:sem.vijverberg@vu.nl> | Room: C-571 | WORKING DAYS: Mo, Tu, We, Fr
VISITING ADDRESS: De Boelelaan 1105, 1081 HV Amsterdam

Op 24 okt. 2018, om 18:45 heeft Clare S. Y. Huang <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi Sem,

Have you solved the issues? Please keep me updated, or I'll close the ticket in 10 days.

Thanks,

Clare

**Comment by csyhuang** [comment]
Hi Sem,

No problem. Please let me know if I can help further.

Best,

Clare

**Comment by semvijverberg** [comment]
Hi Clare,

Yes! The solution by JulienPeloton/s4cmb#11 worked :D. For the anaconda users: 
I did the things in the following order: 
(1) Created a Conda env named FALWA for the FALWA package (https://conda.io/docs/user-guide/tasks/manage-environments.html)
(2) added the path according to JulienPeloton: paste 'export PATH=/usr/bin:$PATH' in your terminal.
(3) used pip install to install it into my conda env: pip install . 

Thanks for your help Clare! Will start working with it, when I'm further with my project.

**Comment by csyhuang** [comment]
Hi Sem, @semvijverberg 

Thanks for the update. Please feel free to contact me if you have any questions regarding the usage of the package. I'm more than happy to help configure the analysis scripts as I've done that for my collaborators. Look forward to hearing about your scientific findings as well.

Cheers,

Clare
