### ISSUE TITLE
header for the compute_reference_states.f90 function

### ISSUE THREAD

**Issue by paologhinassi** [csyhuang/hn2016_falwa#23]
Dear Clare,

thank you for making all functions related to the LWA computation available on git! I am planning to compute the reference state u_ref, theta_ref according to Solomon and Nakamura 2010 part 1 and Huang and Nakamura 2017 and I'd like to use your function. My question is: could you please write a short header/comment for this function explaining the input arguments and what arguments are returned? There are some parameters I cannot guess what they mean (I also don't know fortran very well...). 

Many thanks!

Paolo

**Comment by csyhuang** [comment]
Hi Paolo,

You are not supposed to call the Fortran code but use the python wrapper `QGField` instead. You can refer to the example [here](https://github.com/csyhuang/hn2016_falwa/blob/master/examples/nh2018_science/demo_script_for_nh2018.ipynb). After creating the `QGField` object, call the function `compute_reference_state`. The outputs are `qref`, `uref` and `ptref`.
Do you use python, or you use Fortran only? Let me know how your setting is and I can help you configure your script. You can also reach me at csyhuang@uchicago.edu if you have issues to discuss in private.

**Comment by csyhuang** [comment]
@paologhinassi 

If you instead want to understand what the code `compute_reference_states.f90` is doing, I wrote a note about the equation solver procedures which you may find helpful:

https://github.com/csyhuang/hn2016_falwa/blob/master/notes/SOR_solver_for_NH18.pdf

Let me know if I can help further.

Clare

**Comment by paologhinassi** [comment]
Hello Clare,

great! thank you very much! For now the idea of working on the computation
of the reference state is still an idea for future work. But I am
definitely going to have a look at the wrapper function in python and the
document you've written. In case when I start to play with the code I'll
still need some help I'll let you know. Many thanks for your time! :)

Best,

Paolo

**Comment by csyhuang** [comment]
@paologhinassi 

Sounds good! Just for easy reference, the wrapper function is here (check `def compute_reference_states`):
https://github.com/csyhuang/hn2016_falwa/blob/master/hn2016_falwa/oopinterface.py
I'll close this ticket for now. Thanks and please feel free to post questions here again!
