### ISSUE TITLE
Errors: Calculations in the southern hemisphere

### ISSUE THREAD

**Issue by hungilee** [csyhuang/hn2016_falwa#25]
Hi Clare,

I used GFDL output to run the program and it worked well with only the northern hemisphere. However, there is an error when I turn "northern_hemisphere_results_only" into false. Here I post the error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-60-067887fbeb51> in <module>()
     18     qgpv[tstep, :, :, :], interpolated_u[tstep, :, :, :], interpolated_v[tstep, :, :, :],         interpolated_theta[tstep, :, :, :], static_stability = qgfield_object.interpolate_fields()
     19 
---> 20     qref[tstep, :, :], uref[tstep, :, :], ptref[tstep, :, :] =         qgfield_object.compute_reference_states(northern_hemisphere_results_only=False)
     21 
     22     adv_flux_f1[tstep, :, :],     adv_flux_f2[tstep, :, :],     adv_flux_f3[tstep, :, :],     adv_flux_conv[tstep, :, :],     divergence_eddy_momentum_flux[tstep, :, :],     meridional_heat_flux[tstep, :, :],     lwa_baro[tstep, :, :],     u_baro[tstep, :, :],     lwa[tstep, :, :, :]         = qgfield_object.compute_lwa_and_barotropic_fluxes(northern_hemisphere_results_only=False)

/home/hungi/Documents/Localized_Wave/hn2016_falwa/hn2016_falwa/oopinterface.pyc in compute_reference_states(self, northern_hemisphere_results_only)
    414                                np.swapaxes(self._ptref_temp, 0, 1)))
    415 
--> 416         return self.qref, self.uref, self.ptref
    417 
    418     @property

/home/hungi/Documents/Localized_Wave/hn2016_falwa/hn2016_falwa/oopinterface.pyc in qref(self)
    423         if self._qref is None:
    424             raise ValueError('qref is not computed yet.')
--> 425         return self._return_interp_variables(variable=self._qref, interp_axis=1)
    426 
    427     @property

/home/hungi/Documents/Localized_Wave/hn2016_falwa/hn2016_falwa/oopinterface.pyc in _return_interp_variables(self, variable, interp_axis, northern_hemisphere_results_only)
    299                     variable, self.ylat[-(self.nlat//2+1):],
    300                     self.ylat_no_equator[-(self.nlat//2):],
--> 301                     which_axis=interp_axis)
    302             else:
    303                 return self._interp_back(variable, self.ylat, self.ylat_no_equator, which_axis=interp_axis)

/home/hungi/Documents/Localized_Wave/hn2016_falwa/hn2016_falwa/oopinterface.pyc in _interp_back(self, field, interp_from, interp_to, which_axis)
    226             return interp1d(
    227                 interp_from, field, axis=which_axis, bounds_error=False,
--> 228                 fill_value='extrapolate'
    229             )(interp_to)
    230 

/home/hungi/anaconda2/lib/python2.7/site-packages/scipy/interpolate/interpolate.pyc in __init__(self, x, y, kind, axis, copy, bounds_error, fill_value, assume_sorted)
    431                  assume_sorted=False):
    432         """ Initialize a 1D linear interpolation class."""
--> 433         _Interpolator1D.__init__(self, x, y, axis=axis)
    434 
    435         self.bounds_error = bounds_error  # used by fill_value setter

/home/hungi/anaconda2/lib/python2.7/site-packages/scipy/interpolate/polyint.pyc in __init__(self, xi, yi, axis)
     58         self.dtype = None
     59         if yi is not None:
---> 60             self._set_yi(yi, xi=xi, axis=axis)
     61 
     62     def __call__(self, x):

/home/hungi/anaconda2/lib/python2.7/site-packages/scipy/interpolate/polyint.pyc in _set_yi(self, yi, xi, axis)
    123             shape = (1,)
    124         if xi is not None and shape[axis] != len(xi):
--> 125             raise ValueError("x and y arrays must be equal in length along "
    126                              "interpolation axis.")
    127 

ValueError: x and y arrays must be equal in length along interpolation axis.

**Comment by csyhuang** [comment]
You are using version 0.3.8 - the calculation for the southern hemisphere was not available yet. I ran your code with version 0.4.0 successfully without error.
If you install according to my instructions (i.e. using `python setup.py develop`), you can simply do `git pull` in the repo. Otherwise, please uninstall (`pip uninstall hn2016_falwa`), do `git pull` and reinstall.
