### ISSUE TITLE
application to oceanic simulation

### ISSUE THREAD

**Issue by miniufo** [csyhuang/hn2016_falwa#29]
Hi Clare,

I am interested in your elegent theory and going to give a try in [an idealized oceanic simulation](https://github.com/miniufo/channel).

This is a channel simulation (periodic in zonal direction) on an Beta-plane, a prototype model of Antarctic Circumpolar Current (ACC), which is also close to the context of classical baroclinic instability on midlatitudes.

My simulation is not QG but full dynamics with hydrostatic approximation in a depth coordinate, and definitely away from equator.  I just wonder if the current python code (in QG approximation), tested in atmospheric context, can be adapted to diagnose the FALWA in this ocean simulation?

**Comment by csyhuang** [comment]
Hi @miniufo , would you mind sharing with me what research question are you going to solve with FALWA? Does it involve large-amplitude waves/wave-breaking scenarios?

**Comment by miniufo** [comment]
I am thinking about the diabatic modification of the ACC mean flow, mainly by wind forcing, heat flux at the surface, and internal irreversible mixing.  And how ACC would change under climate change scenario.  To be honest, I am not so sure if all these have been satisfactorily addressed, but I'm pretty sure that the diagnostic framework is suitable for addressing the changes due to diabatic processes.

Right now as a first step I want to calculate the reference state of my ocean simulation in a depth coordinate.  I guess the current python code need to be adapted to that configuration.

I think I could do some contribution if you would like to give some help.  I may try to refactor the code in terms of xarray.

**Comment by csyhuang** [comment]
`Right now as a first step I want to calculate the reference state of my ocean simulation in a depth coordinate. I guess the current python code need to be adapted to that configuration.`

The current code base computes reference states on a sphere (not beta-plane). The boundary conditions are different too, so it would almost be _rewriting_ the equation solver. Given your configuration is zonally periodic, do you really need _**local**_ wave activity? The zonal mean version may be enough for your use case.

Regarding xarray, I have been thinking about writing an interface that operates on xarray too. Thank you for offering to contribute. Let's make sure this is really what you need - we can then make a plan on the coding part.

**Comment by csyhuang** [comment]
Hi @miniufo ,
Since your question is not related to issues/bugs of the package, I would close the ticket and move the discussion to email instead.
Thanks,
Clare

**Comment by miniufo** [comment]
Hi Clare, just an update here.  I've built [a repo](https://github.com/miniufo/xcontour) that can be used to calculate many diagnostics proposed by you and Prof. Nakamura, with the help of `xarray`.

I guess you may be interested in this repo.  I would like to add more functionalities to this package and hope you could give a help if I am facing some problems in doing this (like the issue about local FAWA v.s. local APE #32 ).
