### ISSUE TITLE
Local FAWA v.s. local APE

### ISSUE THREAD

**Issue by miniufo** [csyhuang/hn2016_falwa#32]
Hi, @csyhuang

I've recently notice the possible similarity between your local FAWA and local APE (available potential energy).  After reading two JFM papers by [Scotti and White (2014)](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/diagnosing-mixing-in-stratified-turbulent-flows-with-a-locally-defined-available-potential-energy/17223D6D05A72759B2CC64CA85D1175A) and [Winters and Barkan (2013)](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/available-potential-energy-density-for-boussinesq-fluid-flow/563B240B07CEBFDCD68F77A78FBFED16?__cf_chl_jschl_tk__=pmd_bda924006f9cbd9e7bb065d4ebacdb24faa98adf-1627007878-0-gqNtZGzNAs2jcnBszQli), I found that:
1. both of them defined in a contour-based coordinate;
2. in small-amplitude limits, both of them reduce to the classical definitions;
3. locally positive definite;

Not so sure if we can prove their equivalence mathematically.  But if it is, I think one could use the local FAWA in identifying local internal wave breaking events (vertically), given that it is useful in identifying the local Rossby wave breaking events (horizontally).  Do you have any comments on this?

**Comment by csyhuang** [comment]
Hi @miniufo ,
Since your question is not related to issues/bugs of the package, I would close the ticket and move the discussion to email instead.
Thanks,
Clare
