### ISSUE TITLE
Direct Solver to solve u_ref

### ISSUE THREAD

**Issue by csyhuang** [csyhuang/hn2016_falwa#35]
This is suggestion from Noboru - to implement direct solver to solve uref from elliptic equation. The algorithm is outlined in:

Lindzen, R. S., & Kuo, H. L. (1969). [A reliable method for the numerical integration of a large class of ordinary and partial differential equations](https://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.507.266). In Mon. Wea. Rev.

I would include the Lindzen and Kuo solver as an option in the QGField, such that there are two solvers (SOR v.s. direct solver) user can choose from.

**Comment by miniufo** [comment]
Hi Clare, I've implemented a solver for elliptic equations in GFD using SOR (see [here](https://github.com/miniufo/xinvert)).  I am really interested in the algorithm in this paper.  Just want to know if this has been done or not?  Maybe we could generalize this for many elliptic equations.

**Comment by csyhuang** [comment]
In the latest version of the code v0.6.0, we are using direct matrix inversion instead. Look at
https://github.com/csyhuang/hn2016_falwa/blob/e287b2abbdb407d35ab7dd7fc4fe889c549493e4/hn2016_falwa/oopinterface.py#L823
The matrix is first computed in fortran and then inversion is done by the scipy packages
[```python
            lu, piv, info = dgetrf(qjj)
            qjj, info = dgetri(lu, piv)
```](https://github.com/csyhuang/hn2016_falwa/blob/e287b2abbdb407d35ab7dd7fc4fe889c549493e4/hn2016_falwa/oopinterface.py#L884-L885)
I am going to close this ticket as this issue is solved in the newest release.
