### ISSUE TITLE
Calculation using select pressure levels

### ISSUE THREAD

**Issue by mpecnjak** [csyhuang/hn2016_falwa#41]
Hi @csyhuang,

I am wondering if it is possible to calculate the LWA and the other fields not using all of the 37 pressure levels, but just a select few. For example, I am curious how would the fields look just by using the 4 levels around the jet stream (200, 225, 250 and 300 hPa). I have made some adjustments to the kmax parameter, but I am bit confused about the height adjustments as the first and last height won't be at the surface and top of course. 

I have modified kmax from 49 to 12 as that was the suggestion in the error after I started the code using the wind and temperature fields at these select 4 levels, but then I just got an error for a segmentation fault. Do you have any suggestions on how to adjust it?

I am using a script based on demo_script_for_nh2018.ipynb

Martin

**Comment by csyhuang** [comment]
I realized I forgot to post the reply to your email here. I'll do that and close this ticket:

```
This package is constructed based on the theory, which is derived in the global/hemispheric domain, so it assumes you are putting in data from the whole globe. Even if you are just only interested in signals in a certain region, you still have to fill in the whole globe of data (otherwise global/hemispheric reference state Qref cannot be computed). 

If you really want to use the package to compute wave activity, you may consider filling in synthetic data (which does not affect Qref) for the remaining region if you don't have data for those grid points. However, in that case, you may not be able to use the flux results (since it is based on a global reference state).

Regarding the height interpolation (your previous email), the package assumed evenly spaced vertical grid points in pseudoheight, so the range of pseudoheight you could cover is kmax*dz, and you cannot omit lower-level vertical grid points.
```
