### ISSUE TITLE
Problem using qgfield_object.compute_lwa_and_barotropic_fluxes()  

### ISSUE THREAD

**Issue by AminFazlKazemi** [csyhuang/hn2016_falwa#42]
Hi
This is Amin Fazl Kazemi
I have tried to use calculate fluxes function. I downloaded global ERA5 data on 37 pressure levels, coarsened it to 1.25 degrees, passed it to the program and managed performing qgfield_object.compute_reference_states.
By the way when I pass qgfield_object to compute compute_lwa_and_barotropic_fluxes function, I face a problem :

ValueError: failed in converting 5th argument `qref' of compute_lwa_and_barotropic_fluxes.compute_lwa_and_barotropic_fluxes to C/Fortran array

I wonder the reason. Could you please clarify what I should do. of course the most difficult part (calculating referrence states( are already done, so many many thanks, but as for the addvection terms, I am in trouble. I can send you the file to test is needed.

regards

**Comment by csyhuang** [comment]
Hi Amin,
Sorry for the late response as I was traveling. May you share with me the data you use and your code. From first glance, it looks like data type issue. Would be easiest if I can reproduce your error on my side. If you can put the code and data you use somewhere, maybe on Dropbox or Google Drive and share with me (clare1068@gmail.com), that would be great.
Thanks,
Clare

**Comment by csyhuang** [comment]
Problem is solved as mentioned in #43
