### ISSUE TITLE
possible bug in lwa_theta function

### ISSUE THREAD

**Issue by slubis** [csyhuang/hn2016_falwa#6]
Hi Clare,
I think there might be a bug in the 'lwa_theta' function for the recent version of hn2016_falwa.
Here is the error: 

`File "/home/slubis/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/hn2016_falwa-0.2.0-py2.7.egg/hn2016_falwa/wrapper.py", line 551, in theta_lwa
    n_points, planet_radius=planet_radius)
NameError: global name 'n_points' is not defined`

The function is called by hn2016_falwa.wrapper import theta_lwa.
Thank you,

**Comment by csyhuang** [comment]
Sandro,

Thanks for pointing out. The bug is fixed in v0.2.1. Please clone the updated repo, or you can use this command in the existing cloned repo on your machine:
```
git pull
```
and try reinstall it again. Let me know if there're any issues. Thanks!!

-Clare
