### ISSUE TITLE
Trying to run a notebook in examples/nh2018_science. Unable to import modules: __init__.py refers to modules not present in hn_2016_falwa

### ISSUE THREAD

**Issue by hs2112** [csyhuang/hn2016_falwa#61]
![image](https://user-images.githubusercontent.com/110889718/215022153-3320e84a-5885-4ac2-a1c7-ad111e15fdd3.png)

**Comment by hs2112** [comment]
However, the hn2016_falwa and hn2016_falwa/f90_modules locations seem to contain the related .so and .f90 files, respectively. 

![image](https://user-images.githubusercontent.com/110889718/215022513-f5d19d53-42f0-464b-bb17-1b661025aa4b.png)
![image](https://user-images.githubusercontent.com/110889718/215023341-2352f0a2-3a77-4ac3-b34e-47651327253a.png)

**Comment by hs2112** [comment]
OK so maybe I need to compile the .f90 files separately and store the output in hn2016_falwa? Please let me know if that is right and also the easiest to go about solving this. Thanks!

**Comment by hs2112** [comment]
Two warnings generated upon executing 'python setup.py develop' - 

1. WARN: Could not locate executable armflang
2. hn2016_falwa/f90_modules/interpolate_fields.f90:2:43:

    2 |                               aa, omega, dz, hh, rr, cp, pv, ut, vt, avort, theta, stat)
       |                                                  1
Warning: Unused dummy argument ‘dz’ at (1) [-Wunused-dummy-argument]

**Comment by chpolste** [comment]
Hi, thanks for reporting an issue.

>     2. hn2016_falwa/f90_modules/interpolate_fields.f90:2:43:
>        2 |                               aa, omega, dz, hh, rr, cp, pv, ut, vt, avort, theta, stat)
>        |                                                  1
>        Warning: Unused dummy argument ‘dz’ at (1) [-Wunused-dummy-argument]

This warning should be of no importance.

>     1. WARN: Could not locate executable armflang

This one is more interesting and could potentially take us to the problem: while you have all necessary compiled .so files in your `hn2016_falwa` folder, they were apparently compiled for a x86_64 processor architecture (as you find it in Intel and AMD chips). The warning is about `armflang`, which is a Fortran compiler for the ARM processor architecture (as you find it, e.g., in Apples new M1/M2 chips or the Raspberry Pi). This is a long shot, but are you by any chance on an ARM computer and use a Python version specifically built for ARM? If so, I would guess that your Python is unable to detect/recognize the compiled modules, as they were made for a different architecture.

If possible, can you please run

    python3-config --extension-suffix

and check if the output matches the suffix of the .so files that you have. If the output is different from `.cpython-311-x86_64-linux-gnu.so`, we might have found the problem. Thanks!

**Comment by hs2112** [comment]
@chpolste Thank you for responding so quickly. Running `python3-config --extension-suffix` returned exactly what you have posted. So the __init__ file does not require .py files as modules, the .so files suffice?
![image](https://user-images.githubusercontent.com/110889718/215080477-35e80fd4-d56f-4232-9b83-dacb0f2da4ef.png)

Update: I was able to import the modules. I think adding multiple paths to the system PATH variable did the trick.

**Comment by chpolste** [comment]
Yes, Python is able to directly import the .so files.

Good to hear that you managed to get it running via the PATH variable.

**Comment by csyhuang** [comment]
Thanks @chpolste for solving this issue! Looks like this is solved so I'll close the ticket.
